### ISSUE TITLE
Python38, parsac plotbest error

### ISSUE THREAD

**Issue by fenjuan** [BoldingBruggeman/parsac#4]
_Python versin: 3.8.2 (matplotlib: Version: 3.2.1,netCDF4: Version: 1.5.3)
parsac version: 0.5.4_

**I got the error message when run parsac plotbest:**

``
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\parsac.exe\__main__.py", line 9, in <module>
  File "c:\python38\lib\site-packages\parsac\parsac_run.py", line 12, in main
    parsac.main()
  File "c:\python38\lib\site-packages\parsac\__init__.py", line 48, in main
    args.func(args)
  File "c:\python38\lib\site-packages\parsac\result\plotbest.py", line 137, in main
    t_interfaces = pylab.date2num(t_interfaces)
  File "c:\python38\lib\site-packages\matplotlib\dates.py", line 437, in date2num
    return _to_ordinalf_np_vectorized(d)
  File "c:\python38\lib\site-packages\numpy\lib\function_base.py", line 2091, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "c:\python38\lib\site-packages\numpy\lib\function_base.py", line 2161, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "c:\python38\lib\site-packages\numpy\lib\function_base.py", line 2121, in _get_ufunc_and_otypes
    outputs = func(*inputs)
  File "c:\python38\lib\site-packages\matplotlib\dates.py", line 222, in _to_ordinalf
    base = float(dt.toordinal())
AttributeError: 'cftime._cftime.DatetimeGregorian' object has no attribute 'toordinal'
'''
**And I have digged a bit into the issue, and I think the problems might lie in the cftime num2date function. Since the current version of num2date function in cftime has default values of 'only_use_cftime_datetimes=True, only_use_python_datetimes=False', while the former version was oppsite.
I did a small experiment here:** 

``
>>> import cftime
>>> dates =cftime.num2date(30000,units = 'hours since 1990-1-1')
>>> print(dates)
1993-06-04 00:00:00
>>> type(dates)
<class 'cftime._cftime.DatetimeGregorian'>
>>> dates.toordinal()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'cftime._cftime.DatetimeGregorian' object has no attribute 'toordinal'
>>> dates_py = cftime.num2pydate(30000,units = 'hours since 1990-1-1')
>>> print(dates_py)
1993-06-04 00:00:00
>>> dates_py.toordinal()
727718
>>>
``
**So maybe while pylab.date2num function process the dates, it can not find the correct format of t_interfaces? **

Best regards
Fen

**Comment by fenjuan** [comment]
Was setting up another computer for parsac, and exact same error happened, 

Python versin: 3.7.0 (matplotlib: Version: 3.2.1,netCDF4: Version: 1.5.3)
parsac version: 0.5.4

**Comment by jornbr** [comment]
Hi Fen, thanks for the detailed analysis. It definitely looks like an incompatibility between NetCDF4's num2date and matplotlib's date2num. The best solution seems to add only_use_python_datetimes=True whenever we call num2date, as you suggest. I'll add that.

Cheers

Jorn

**Comment by fenjuan** [comment]
Hej Jorn
   Let me know when you fix this. Since I did a quick fix in my plotbest plot, and I got another error, I hope it's not a new one but due to I fixed in wrong place.

Cheers 
Fen

**Comment by jornbr** [comment]
Hi Fen. This is hopefully fixed in parsac 0.5.5. Please try "pip install parsac --upgrade"

**Comment by fenjuan** [comment]
Hi Jorn
   I am afraid the problems is still there. In plotbest.py line 137, the function of pylab.date2num. Sees like t_interfaces still have formate of cftime._cftime.DatetimeGregorian. (I think t_interfaces should be 'cftime._cftime.real_datetime' to use toordinal)
   Another solution for  only_use_python_datetimes=True is use num2pydate instead of num2date.


Best 
Fen

**Comment by jornbr** [comment]
Hi Fen, the trouble with both num2pydate and only_use_python_datetimes is that they were introduced relatively recently - using them would therefore limit parsac to recent versions of netCDF4 - something I'd ideally avoid. The patch I committed therefore sets only_use_cftime_datetimes (which has been around longer) to False, which according to the documentation should generate native python datetime objects. Not sure why that is not happening - I'll take another look

Jorn

**Comment by fenjuan** [comment]
Hi Jorn
 I found a local solution, I downgraded my cftime version to 1.0. I think the thing of the default time type change for cftime num2date is after version 1.1. I downgraded to 1.0.3.4. I chose the version number simply because it's the version currently installed in one of our machines, and works.

Best 
Fen

**Comment by jornbr** [comment]
Hi Fen,

Good to hear that downgrading cftime worked for you. When you were still using the more recent version, I think you may have run into a cftime bug that was only fixed very recently (in 1.1.2):

https://github.com/Unidata/cftime/issues/165

That would mean that the current parsac solution is ok - it's just a matter of avoiding particular cftime versions (at least 1.1.1.2).

Cheers,

Jorn
